from flask import Flask, render_template, jsonify, request, redirect, session, send_file
from functools import wraps
import json
import requests
import csv
from datetime import datetime
from io import StringIO, BytesIO
import os
from werkzeug.security import generate_password_hash, check_password_hash
from collections import deque
import threading

# =============================
# MINIATURE GRID FAULT DIAGNOSTICS & AI PREDICTION
# =============================
def diagnose_fault(voltage, current, frequency):
    faults = []
    tips = []
    # Voltage diagnostics (miniature grid: 11-28V)
    if voltage < 11:
        faults.append("UNDERVOLTAGE_FAULT")
        tips.append("Check for weak supply or excessive load.")
    elif voltage > 28:
        faults.append("OVERVOLTAGE_FAULT")
        tips.append("Disconnect unnecessary sources or check regulator.")
    # Current diagnostics (miniature grid: <2A)
    if current > 2:
        faults.append("OVERCURRENT_FAULT")
        tips.append("Reduce load or check for short circuit.")
    elif current < 0.05 and voltage > 0:
        faults.append("OPEN_CIRCUIT_FAULT")
        tips.append("Check wiring and connections for open circuit.")
    # Frequency diagnostics (if AC)
    if frequency < 49 or frequency > 51:
        faults.append("FREQUENCY_FAULT")
        tips.append("Check inverter or signal generator stability.")
    if not faults:
        faults.append("NORMAL")
        tips.append("System operating normally.")
    return faults, tips

# Stub for AI prediction (replace with real model if available)

def ai_predict_fault(voltage, current, frequency):
    if voltage > 28 or current > 2:
        return "FAULT_PREDICTED"
    return "NO_FAULT_PREDICTED"





app = Flask(__name__)
app.secret_key = "my_super_secure_key_12345"  # Change this to a secure key


# ==========================================================
# LOAD MODEL RESULTS (generated by train.py)
# ==========================================================
results = json.load(open("model_results.json"))


# ==========================================================
# HARDWARE DATA STORAGE (In-Memory)
# ==========================================================
hardware_data = {
    "voltage": 0,
    "current": 0,
    "frequency": 0,
    "fault": "UNKNOWN",
    "timestamp": datetime.now().isoformat(),
    "status": "DISCONNECTED"
}
hardware_history = deque(maxlen=500)
data_lock = threading.Lock()


# ==========================================================
# USER AUTHENTICATION DATABASE (In-memory for demo)
# ==========================================================
USERS = {
    "admin": generate_password_hash("admin123"),
    "user": generate_password_hash("user123")
}


# ==========================================================
# LOGIN REQUIRED DECORATOR
# ==========================================================
def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "user" not in session:
            return redirect("/login")
        return f(*args, **kwargs)
    return decorated_function


# ==========================================================
# ROUTES
# ==========================================================

@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        if username in USERS and check_password_hash(USERS[username], password):
            session["user"] = username
            session["is_admin"] = (username == "admin")
            return redirect("/")
        else:
            return render_template("login.html", error="Invalid credentials")
    
    return render_template("login.html")

@app.route("/logout")
def logout():
    session.clear()
    return redirect("/login")

@app.route("/")
@login_required
def index():
    """Main dashboard page"""
    return render_template(
        "w.html",
        best_model=results["best_model"],
        best_accuracy=results["best_accuracy"],
        all_accuracies=results["all_accuracies"]
    )

@app.route("/analytics")
@login_required
def analytics():
    return render_template("analytics.html")

@app.route("/models")
@login_required
def models_page():
    return render_template(
        "models.html",
        best_model=results["best_model"],
        best_accuracy=results["best_accuracy"],
        all_accuracies=results["all_accuracies"]
    )

@app.route("/alerts")
@login_required
def alerts_page():
    return render_template("alerts.html")




@app.route("/settings")
@login_required
def settings_page():
    return render_template("settings.html")

# ==========================================================
# FAULT PREVENTION PAGE ROUTE (CORRECT LOCATION)
# ==========================================================
@app.route("/prevention")
@login_required
def prevention_page():
    return render_template(
        "prevention.html",
        best_model=results["best_model"],
        best_accuracy=results["best_accuracy"],
        all_accuracies=results["all_accuracies"]
    )

# ==========================================================
# ANALYTICS API
# ==========================================================

@app.route("/api/analytics")
@login_required
def get_analytics():
    """Returns analytics data for the analytics page"""
    try:
        with data_lock:
            if not hardware_history:
                return jsonify({
                    "stats": {
                        "voltage": {"min": 0, "max": 0, "avg": 0},
                        "current": {"min": 0, "max": 0, "avg": 0},
                        "frequency": {"min": 0, "max": 0, "avg": 0},
                        "total_readings": 0
                    },
                    "voltage_distribution": [],
                    "current_distribution": [],
                    "fault_counts": [],
                    "fault_categories": [],
                    "hourly_data": [{"name": "Voltage", "data": []}, {"name": "Current", "data": []}]
                })
            
            # Calculate statistics
            voltages = [r["voltage"] for r in hardware_history]
            currents = [r["current"] for r in hardware_history]
            frequencies = [r["frequency"] for r in hardware_history]
            faults = [r["fault"] for r in hardware_history]

            # Count fault types
            fault_counts = {}
            for fault in faults:
                fault_counts[fault] = fault_counts.get(fault, 0) + 1

            stats = {
                "voltage": {
                    "min": min(voltages) if voltages else 0,
                    "max": max(voltages) if voltages else 0,
                    "avg": sum(voltages) / len(voltages) if voltages else 0
                },
                "current": {
                    "min": min(currents) if currents else 0,
                    "max": max(currents) if currents else 0,
                    "avg": sum(currents) / len(currents) if currents else 0
                },
                "frequency": {
                    "min": min(frequencies) if frequencies else 0,
                    "max": max(frequencies) if frequencies else 0,
                    "avg": sum(frequencies) / len(frequencies) if frequencies else 0
                },
                "total_readings": len(hardware_history)
            }

            return jsonify({
                "stats": stats,
                "voltage_distribution": voltages[-50:] if len(voltages) > 50 else voltages,
                "current_distribution": currents[-50:] if len(currents) > 50 else currents,
                "fault_counts": list(fault_counts.values()),
                "fault_categories": list(fault_counts.keys()),
                "hourly_data": [
                    {"name": "Voltage", "data": voltages[-24:] if len(voltages) > 24 else voltages},
                    {"name": "Current", "data": currents[-24:] if len(currents) > 24 else currents}
                ]
            })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# ==========================================================
# ALERTS API
# ==========================================================

# Store alerts in memory
alerts_history = deque(maxlen=1000)

@app.route("/api/alerts")
@login_required
def get_alerts():
    """Returns all alerts"""
    try:
        with data_lock:
            # Generate alerts from recent faults
            recent_alerts = []
            fault_types = {
                'SHORT_CIRCUIT_FAULT': {'type': 'critical', 'icon': 'fa-exclamation-circle', 'title': 'Short Circuit'},
                'HIGH_VOLTAGE_FAULT': {'type': 'critical', 'icon': 'fa-lightning-bolt', 'title': 'High Voltage'},
                'OPEN_VOLTAGE_FAULT': {'type': 'warning', 'icon': 'fa-exclamation-triangle', 'title': 'Open Circuit'},
                'FREQUENCY_FAULT': {'type': 'warning', 'icon': 'fa-wave-square', 'title': 'Frequency Unstable'},
                'NORMAL': {'type': 'info', 'icon': 'fa-check-circle', 'title': 'System Normal'}
            }
            
            for reading in list(hardware_history)[-50:]:
                fault = reading['fault']
                if fault in fault_types:
                    alert_info = fault_types[fault]
                    recent_alerts.append({
                        'type': alert_info['type'],
                        'icon': alert_info['icon'],
                        'title': alert_info['title'],
                        'description': f"Fault detected: {fault}",
                        'timestamp': reading['timestamp'],
                        'resolved': fault == 'NORMAL'
                    })
            
            return jsonify({"alerts": recent_alerts})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# ==========================================================
# HARDWARE DATA RECEPTION ENDPOINT
# ==========================================================

@app.route("/api/hardware/data", methods=["POST"])
def receive_hardware_data():
    """
    Endpoint to receive live hardware data from test.py
    Expected JSON: {
        "voltage": float,
        "current": float,
        "frequency": float,
        "fault": string
    }
    """
    global hardware_data, hardware_history
    
    try:
        data = request.get_json()
        
        # Validate data
        if not all(key in data for key in ["voltage", "current", "frequency", "fault"]):
            return jsonify({"error": "Missing required fields"}), 400
        
        # Update hardware data with thread safety
        with data_lock:
            hardware_data["voltage"] = float(data["voltage"])
            hardware_data["current"] = float(data["current"])
            hardware_data["frequency"] = float(data["frequency"])
            hardware_data["fault"] = str(data["fault"])
            hardware_data["timestamp"] = datetime.now().isoformat()
            hardware_data["status"] = "CONNECTED"
            
            # Store in history
            hardware_history.append({
                "voltage": hardware_data["voltage"],
                "current": hardware_data["current"],
                "frequency": hardware_data["frequency"],
                "fault": hardware_data["fault"],
                "timestamp": hardware_data["timestamp"]
            })
        
        return jsonify({"status": "SUCCESS", "message": "Data received"}), 200
        
    except Exception as e:
        print(f"Error receiving hardware data: {e}")
        return jsonify({"status": "ERROR", "message": str(e)}), 500


# LIVE API for dashboard - Read from hardware
@app.route("/live-data")
@login_required
def live_data():
    """Returns current hardware readings"""
    try:
        with data_lock:
            return jsonify({
                "voltage": hardware_data["voltage"],
                "current": hardware_data["current"],
                "frequency": hardware_data["frequency"],
                "fault": hardware_data["fault"],
                "timestamp": hardware_data["timestamp"],
                "status": hardware_data["status"]
            })
    except Exception as e:
        return jsonify({"status": "ERROR", "message": str(e)}), 500


@app.route("/api/hardware/history")
@login_required
def get_hardware_history():
    """Returns last N readings from hardware"""
    try:
        limit = request.args.get('limit', 100, type=int)
        with data_lock:
            history = list(hardware_history)[-limit:]
        return jsonify({"data": history, "count": len(history)})
    except Exception as e:
        return jsonify({"status": "ERROR", "message": str(e)}), 500

# ==========================================================
# DATA EXPORT ROUTES
# ==========================================================

@app.route("/export")
@login_required
def export_page():
    return render_template("export.html")

@app.route("/api/export/csv")
@login_required
def export_csv():
    try:
        # Create CSV from hardware history
        output = StringIO()
        writer = csv.writer(output)
        writer.writerow(["Timestamp", "Voltage (V)", "Current (mA)", "Frequency (Hz)", "Status"])
        
        with data_lock:
            for reading in hardware_history:
                writer.writerow([
                    reading.get("timestamp", ""),
                    reading.get("voltage", ""),
                    reading.get("current", ""),
                    reading.get("frequency", ""),
                    reading.get("fault", "")
                ])

        output.seek(0)
        mem = BytesIO()
        mem.write(output.getvalue().encode('utf-8'))
        mem.seek(0)

        return send_file(
            mem,
            mimetype="text/csv",
            as_attachment=True,
            download_name=f"smartgrid_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        )
    except Exception as e:
        return jsonify({"status": "ERROR", "message": str(e)}), 500

@app.route("/api/export/json")
@login_required
def export_json():
    try:
        with data_lock:
            export_data = {
                "channel": "SmartGrid Local Hardware",
                "device": "ESP32 Microcontroller",
                "export_time": datetime.now().isoformat(),
                "total_readings": len(hardware_history),
                "feeds": list(hardware_history)
            }

        filename = f"smartgrid_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        mem = BytesIO()
        mem.write(json.dumps(export_data, indent=2).encode('utf-8'))
        mem.seek(0)

        return send_file(
            mem,
            mimetype="application/json",
            as_attachment=True,
            download_name=filename
        )
    except Exception as e:
        return jsonify({"status": "ERROR", "message": str(e)}), 500

# ==========================================================
# ADMIN PANEL ROUTES
# ==========================================================

@app.route("/admin")
@login_required
def admin_panel():
    if not session.get("is_admin"):
        return "Unauthorized", 403
    
    return render_template(
        "admin.html",
        best_model=results["best_model"],
        best_accuracy=results["best_accuracy"],
        all_accuracies=results["all_accuracies"]
    )

@app.route("/api/admin/stats")
@login_required
def admin_stats():
    if not session.get("is_admin"):
        return jsonify({"error": "Unauthorized"}), 403

    try:
        with data_lock:
            if not hardware_history:
                return jsonify({
                    "total_readings": 0,
                    "voltage": {"min": 0, "max": 0, "avg": 0},
                    "current": {"min": 0, "max": 0, "avg": 0},
                    "frequency": {"min": 0, "max": 0, "avg": 0}
                })
            
            # Calculate statistics from hardware history
            voltages = [r["voltage"] for r in hardware_history]
            currents = [r["current"] for r in hardware_history]
            frequencies = [r["frequency"] for r in hardware_history]

            stats = {
                "total_readings": len(hardware_history),
                "voltage": {
                    "min": min(voltages) if voltages else 0,
                    "max": max(voltages) if voltages else 0,
                    "avg": sum(voltages) / len(voltages) if voltages else 0
                },
                "current": {
                    "min": min(currents) if currents else 0,
                    "max": max(currents) if currents else 0,
                    "avg": sum(currents) / len(currents) if currents else 0
                },
                "frequency": {
                    "min": min(frequencies) if frequencies else 0,
                    "max": max(frequencies) if frequencies else 0,
                    "avg": sum(frequencies) / len(frequencies) if frequencies else 0
                }
            }

        return jsonify(stats)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route("/api/admin/users")
@login_required
def get_users():
    if not session.get("is_admin"):
        return jsonify({"error": "Unauthorized"}), 403
    
    return jsonify({
        "users": [
            {"username": "admin", "is_admin": True},
            {"username": "user", "is_admin": False}
        ]
    })


# ==========================================================
# DIAGNOSTICS API ENDPOINT (MOVED UP TO AVOID FLASK ASSERTION ERROR)
# ==========================================================

# ==========================================================
# ERROR HANDLERS
# ==========================================================

@app.errorhandler(404)
def not_found(error):
    return render_template("404.html"), 404

@app.errorhandler(500)
def server_error(error):
    return render_template("500.html"), 500

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)